//  MacroIndicators.swift
//  WealthPolicyDesk
//
//  The macro indicator catalog — ~61 observable US business-cycle indicators, one
//  declarative row each (value + bands + importance + odds weight + source). A
//  dated snapshot generated from FRED / Treasury / market data; VERIFY before use.
//  Regenerate the values out-of-band (the app stays offline). See MacroModel.swift.

import Foundation

public extension Seed {
    /// The data-as-of date of the board below — the latest observation across the
    /// machine-refreshed FRED/Shiller series, NOT the plan date. This is what every
    /// "as of" caption should show; `generate_cme_snapshot.py` rewrites it on refresh.
    static let macroDataAsOf: IsoDate = "2026-08-20"

    /// The current macro indicator board (FRED/Shiller refresh 2026-08-20; ISM/LEI/proxy rows still "verify").
    static let macroIndicators: [MacroIndicator] = [
        // --- Growth & activity ---
        MacroIndicator("ISM mfg new orders", .growth, 56.7, .index, importance: 3, oddsWeight: 8, timing: .leading, source: "estimate",
            descriptor: "Forward-looking demand pipeline of the ISM factory survey; the single best-leading PMI component — >53 signals accelerating orders and early/mid expansion, <45 flags contraction.",
            bands: [MacroBand(45, .recession, "contracting"), MacroBand(50, .late, "shrinking"), MacroBand(53, .neutral, "flat"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("ISM mfg headline", .growth, 52, .index, importance: 2, oddsWeight: 5, timing: .leading, source: "estimate",
            descriptor: "Composite manufacturing PMI (50 = breakeven); a widely-watched cyclical pulse — sustained readings under 45 have coincided with most postwar recessions.",
            bands: [MacroBand(45, .recession, "deep contraction"), MacroBand(50, .late, "softening"), MacroBand(53, .neutral, "steady"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("ISM services PMI", .growth, 53.6, .index, importance: 2, oddsWeight: 4, timing: .leading, source: "estimate",
            descriptor: "Non-manufacturing PMI covering ~70% of GDP; services rarely contract, so a break below ~48 is a broad, high-signal warning of a stalling economy.",
            bands: [MacroBand(46, .recession, "contracting"), MacroBand(50, .late, "softening"), MacroBand(53, .neutral, "steady"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("Industrial production YoY", .growth, 1.08, .pct, importance: 2, oddsWeight: 0, timing: .coincident, source: "INDPRO",
            descriptor: "Year-over-year output of factories, mines and utilities; a core NBER coincident series — negative YoY confirms recession but lags, so it carries no forward-odds weight.",
            bands: [MacroBand(-1.5, .recession, "contracting"), MacroBand(0.5, .late, "stalling"), MacroBand(2, .neutral, "modest growth"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("CFNAI activity factor", .growth, -0.05, .index, importance: 3, oddsWeight: 8, timing: .coincident, source: "CFNAIMA3",
            descriptor: "Chicago Fed National Activity Index — a weighted factor of 85 monthly series (0 = trend growth); its 3-month average below -0.70 is a textbook recession-onset trigger.",
            bands: [MacroBand(-0.7, .recession, "contraction"), MacroBand(-0.2, .late, "below trend"), MacroBand(0.2, .neutral, "trend growth"), MacroBand(999999, .early, "above trend")]),
        MacroIndicator("Real retail sales YoY", .growth, 1.65, .pct, importance: 2, oddsWeight: 0, timing: .coincident, source: "RRSFS",
            descriptor: "Inflation-adjusted retail and food-services sales YoY; a direct read on the consumer engine — moderate positive growth signals a firm, still-spending household sector.",
            bands: [MacroBand(-1, .recession, "contracting"), MacroBand(0.5, .late, "stalling"), MacroBand(2.5, .neutral, "moderate"), MacroBand(999999, .early, "robust")]),
        MacroIndicator("Core capital-goods orders", .growth, 12.94, .pct, importance: 2, oddsWeight: 3, timing: .leading, source: "NEWORDER",
            descriptor: "New orders for nondefense capital goods ex-aircraft, YoY — the business-investment pipeline and an LEI leading component; a sharp roll-over precedes capex-led downturns.",
            bands: [MacroBand(-3, .recession, "orders falling"), MacroBand(0, .late, "flat"), MacroBand(2.5, .neutral, "modest"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("Capacity utilization", .growth, 76.29, .pct, importance: 1, oddsWeight: 0, timing: .coincident, source: "TCU",
            descriptor: "Share of industrial capacity in use (long-run avg ~79.6%); a coincident gauge of slack — falling utilization flags weakening demand, while readings near average confirm a firm, non-overheating economy.",
            bands: [MacroBand(72, .recession, "deep slack"), MacroBand(76, .late, "slack building"), MacroBand(79, .neutral, "near average"), MacroBand(999999, .early, "high utilization")]),
        // --- Labor ---
        MacroIndicator("Sahm rule", .labor, -0.03, .pct, importance: 3, oddsWeight: 22, timing: .lagging, source: "SAHMCURRENT",
            descriptor: "Rise in the 3mo-avg unemployment rate above its trailing-12mo low; crossing 0.50 has flagged every recession since 1970 — below that line the labor market shows no crack, and the distance to the trigger is the read.",
            bands: [MacroBand(0.2, .early, "healthy"), MacroBand(0.35, .neutral, "steady"), MacroBand(0.5, .late, "softening"), MacroBand(999999, .recession, "triggered")]),
        MacroIndicator("Initial claims 13wk chg", .labor, -1.9, .pct, importance: 3, oddsWeight: 18, timing: .leading, source: "ICSA",
            descriptor: "13-week percent change in initial jobless claims — the fastest labor leading indicator, turning up before the Sahm rule fires. A falling trend means firms aren't shedding workers.",
            bands: [MacroBand(-3, .early, "declining"), MacroBand(6, .neutral, "flat"), MacroBand(15, .late, "rising"), MacroBand(999999, .recession, "surging")]),
        MacroIndicator("Continuing claims", .labor, 1799, .levelK, importance: 2, oddsWeight: 5, timing: .coincident, source: "CCSA",
            descriptor: "Number still collecting unemployment insurance; measures how hard re-employment is. Drifting up in a low-hire market but not yet elevated.",
            bands: [MacroBand(1700, .early, "low"), MacroBand(1950, .neutral, "moderate"), MacroBand(2100, .late, "elevated"), MacroBand(999999, .recession, "climbing")]),
        MacroIndicator("Payrolls 3mo avg", .labor, 20, .levelK, importance: 3, oddsWeight: 12, timing: .coincident, source: "PAYEMS",
            descriptor: "3-month average monthly nonfarm payroll gain — the headline pace of job creation; a cushion above ~175k/mo is comfortably expansionary, while a slide toward zero flags a stalling labor market.",
            bands: [MacroBand(0, .recession, "contracting"), MacroBand(75, .late, "stalling"), MacroBand(175, .neutral, "moderate"), MacroBand(999999, .early, "robust")]),
        MacroIndicator("Unemployment trend", .labor, -0.2, .pct, importance: 2, oddsWeight: 6, timing: .lagging, source: "UNRATE",
            descriptor: "12-month change in the unemployment rate — direction beats level: a rising trend signals labor deterioration, while a flat-to-falling trend is consistent with a firm labor market.",
            bands: [MacroBand(-0.2, .early, "falling"), MacroBand(0.25, .neutral, "stable"), MacroBand(0.5, .late, "rising"), MacroBand(999999, .recession, "climbing")]),
        MacroIndicator("Temp-help employment", .labor, -0.5, .pct, importance: 2, oddsWeight: 8, timing: .leading, source: "estimate",
            descriptor: "Year-over-year change in temporary-help services jobs — firms cut flexible temps before permanent staff, so it leads headcount. Slightly soft but stabilized, not collapsing.",
            bands: [MacroBand(-8, .recession, "collapsing"), MacroBand(-2, .late, "declining"), MacroBand(2, .neutral, "flat"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("Avg weekly hours", .labor, 34.3, .index, importance: 2, oddsWeight: 6, timing: .leading, source: "AWHAETP",
            descriptor: "Average weekly hours of private employees, an LEI component — employers trim hours before jobs, so falling hours precede layoffs while steady hours signal firms are still holding their workforce.",
            bands: [MacroBand(33.8, .recession, "hours slashed"), MacroBand(34.1, .late, "softening"), MacroBand(34.5, .neutral, "steady"), MacroBand(999999, .early, "strong")]),
        MacroIndicator("JOLTS quits rate", .labor, 2, .pct, importance: 2, oddsWeight: 4, timing: .leading, source: "JTSQUR",
            descriptor: "Share of workers voluntarily quitting each month — a confidence gauge, since people quit when they can find better jobs; a rate near pre-pandemic norms signals a healthy, mobile labor market, and a sharp drop marks fading worker confidence.",
            bands: [MacroBand(1.6, .recession, "frozen"), MacroBand(2, .late, "cooling"), MacroBand(2.4, .neutral, "normal"), MacroBand(999999, .early, "hot")]),
        // --- Housing ---
        MacroIndicator("Building permits", .housing, 1443, .levelK, importance: 3, oddsWeight: 8, timing: .leading, source: "PERMIT",
            descriptor: "New privately-owned units authorized by permit (SAAR); a Conference Board LEI component and the cleanest housing leader — permits are pulled before ground breaks, so they turn ahead of construction and the cycle.",
            bands: [MacroBand(1000, .recession, "collapsing"), MacroBand(1250, .late, "softening"), MacroBand(1500, .neutral, "steady"), MacroBand(1650, .early, "firm"), MacroBand(999999, .early, "booming")]),
        MacroIndicator("Housing starts", .housing, 1239, .levelK, importance: 2, oddsWeight: 5, timing: .leading, source: "HOUST",
            descriptor: "New residential construction started (SAAR); rate-sensitive real activity that swings hard in downturns as builders pull back, though it lags permits by a month or two.",
            bands: [MacroBand(900, .recession, "collapsing"), MacroBand(1200, .late, "slowing"), MacroBand(1500, .neutral, "steady"), MacroBand(1700, .early, "strong"), MacroBand(999999, .early, "booming")]),
        MacroIndicator("NAHB builder sentiment", .housing, 46, .index, importance: 2, oddsWeight: 4, timing: .leading, source: "estimate",
            descriptor: "NAHB/Wells Fargo Housing Market Index of single-family builder confidence (50 = neutral); a forward read on buyer traffic and sales expectations that leads starts.",
            bands: [MacroBand(25, .recession, "depressed"), MacroBand(43, .late, "soft"), MacroBand(56, .neutral, "balanced"), MacroBand(65, .early, "optimistic"), MacroBand(999999, .early, "booming")]),
        MacroIndicator("New home sales", .housing, 628, .levelK, importance: 2, oddsWeight: 3, timing: .leading, source: "HSN1F",
            descriptor: "New single-family houses sold (SAAR); demand-side gauge sensitive to mortgage rates and jobs — builder rate buydowns have kept it firm despite restrictive financing.",
            bands: [MacroBand(400, .recession, "collapsing"), MacroBand(550, .late, "soft"), MacroBand(750, .neutral, "steady"), MacroBand(850, .early, "strong"), MacroBand(999999, .early, "booming")]),
        MacroIndicator("30y mortgage rate", .housing, 6.65, .pct, importance: 2, oddsWeight: 0, timing: .leading, source: "MORTGAGE30US",
            descriptor: "Freddie Mac average 30-year fixed rate; the price of housing credit — an elevated rate and primary-secondary spread keep financing restrictive, the classic late-cycle drag on affordability and refi.",
            bands: [MacroBand(4, .early, "stimulative"), MacroBand(5.5, .neutral, "normal"), MacroBand(6.5, .late, "restrictive"), MacroBand(999999, .late, "very restrictive")]),
        // --- Consumer ---
        MacroIndicator("Conf Board expectations", .consumer, 88, .index, importance: 2, oddsWeight: 5, timing: .leading, source: "estimate",
            descriptor: "Conference Board's forward-looking gauge of consumers' 6-month outlook for business, jobs and income; a leading consumer signal — readings under 80 have historically preceded recessions, so proximity to that line is the warning read.",
            bands: [MacroBand(80, .recession, "recession warning"), MacroBand(95, .neutral, "guarded"), MacroBand(110, .early, "improving"), MacroBand(999999, .early, "optimistic")]),
        MacroIndicator("Conf Board present situation", .consumer, 138, .index, importance: 1, oddsWeight: 0, timing: .coincident, source: "estimate",
            descriptor: "Conference Board's read on how consumers rate current business and labor conditions (jobs plentiful vs. hard-to-get); a coincident marker of where the cycle stands now — high readings reflect a firm labor backdrop, and a slide marks deterioration.",
            bands: [MacroBand(85, .recession, "contracting"), MacroBand(115, .late, "softening"), MacroBand(135, .neutral, "steady"), MacroBand(999999, .early, "strong")]),
        MacroIndicator("UMich sentiment", .consumer, 49.5, .index, importance: 2, oddsWeight: 3, timing: .leading, source: "UMCSENT",
            descriptor: "University of Michigan's broad consumer sentiment index — a leading gauge whose swings in mood foreshadow discretionary spending; depressed readings weigh on demand and often precede a pullback, while a durable rise in sentiment tends to lead firmer spending.",
            bands: [MacroBand(55, .recession, "depressed"), MacroBand(75, .neutral, "cautious"), MacroBand(90, .early, "improving"), MacroBand(999999, .early, "buoyant")]),
        MacroIndicator("Real personal income", .consumer, 0.14, .pct, importance: 2, oddsWeight: 6, timing: .coincident, source: "W875RX1",
            descriptor: "Inflation-adjusted household income excluding government transfers (YoY), a core NBER coincident recession marker — sustained declines signal contraction, while positive growth confirms real purchasing power is still expanding.",
            bands: [MacroBand(-0.5, .recession, "contracting"), MacroBand(1, .late, "stalling"), MacroBand(2.6, .neutral, "steady"), MacroBand(999999, .early, "expanding")]),
        MacroIndicator("Real personal spending", .consumer, 2.54, .pct, importance: 2, oddsWeight: 4, timing: .coincident, source: "PCEC96",
            descriptor: "Inflation-adjusted consumer spending (real PCE, YoY), ~68% of GDP; its trend is the single best coincident read on demand momentum — firm positive growth is consistent with a healthy expansion, a roll-over marks weakening demand.",
            bands: [MacroBand(-0.5, .recession, "contracting"), MacroBand(1.2, .late, "slowing"), MacroBand(2.4, .neutral, "steady"), MacroBand(999999, .early, "resilient")]),
        MacroIndicator("Retail control group", .consumer, 3.9, .pct, importance: 2, oddsWeight: 3, timing: .coincident, source: "estimate",
            descriptor: "Retail-sales control group (ex autos, gas, building materials, food services; YoY) that feeds directly into GDP; a timely pulse on core goods demand — firm growth signals no consumer retrenchment, a decline flags pull-back.",
            bands: [MacroBand(0, .recession, "contracting"), MacroBand(2, .late, "soft"), MacroBand(3.5, .neutral, "steady"), MacroBand(999999, .early, "firm")]),
        MacroIndicator("Credit-card delinquencies", .consumer, 2.92, .pct, importance: 2, oddsWeight: 4, timing: .lagging, source: "DRCCLACBS",
            descriptor: "Share of credit-card balances past due at commercial banks (higher = later); rising delinquencies flag late-cycle consumer stress and tightening household budgets — levels above pre-pandemic norms are the marginal late-cycle read within an otherwise firm consumer.",
            bands: [MacroBand(2, .early, "pristine"), MacroBand(2.8, .neutral, "normalizing"), MacroBand(4, .late, "elevated"), MacroBand(999999, .recession, "distressed")]),
        // --- Inflation ---
        MacroIndicator("Headline CPI YoY", .inflation, 3.3, .pct, importance: 2, oddsWeight: 0, timing: .lagging, source: "CPIAUCSL",
            descriptor: "Total consumer-price inflation year-over-year; the headline cost-of-living gauge — accelerating prints signal late-cycle overheating and coming policy restraint, deflation signals demand collapse.",
            bands: [MacroBand(0, .recession, "deflation"), MacroBand(1.5, .early, "below target"), MacroBand(3, .neutral, "near target"), MacroBand(4.5, .late, "elevated"), MacroBand(999999, .late, "overheating")]),
        MacroIndicator("Core CPI YoY", .inflation, 2.47, .pct, importance: 1, oddsWeight: 0, timing: .lagging, source: "CPILFESL",
            descriptor: "CPI excluding food and energy; strips volatile components to reveal the underlying sticky-inflation trend that drives Fed policy and late-cycle risk — still running above target here.",
            bands: [MacroBand(0.5, .recession, "deflationary"), MacroBand(1.8, .early, "slack/soft"), MacroBand(3.2, .neutral, "sticky, near target"), MacroBand(4.5, .late, "firm/broadening"), MacroBand(999999, .late, "overheating")]),
        MacroIndicator("Core PCE YoY", .inflation, 3.29, .pct, importance: 2, oddsWeight: 0, timing: .lagging, source: "PCEPILFE",
            descriptor: "The Fed's preferred inflation gauge (personal-consumption prices ex food and energy); its distance from the 2% goal sets the policy stance that ultimately turns the cycle — currently just above target and easing.",
            bands: [MacroBand(0.5, .recession, "deflation"), MacroBand(1.6, .early, "below target"), MacroBand(2.8, .neutral, "near 2% goal"), MacroBand(4, .late, "above target/firm"), MacroBand(999999, .late, "overheating")]),
        MacroIndicator("10y breakeven", .inflation, 2.34, .pct, importance: 2, oddsWeight: 5, timing: .leading, source: "T10YIE",
            descriptor: "Market-implied average inflation over 10 years (nominal Treasury minus TIPS yield); forward-looking expectations — a collapse toward deflation warns of a demand shock, a surge signals de-anchoring, and readings near the 2% target signal well-behaved expectations.",
            bands: [MacroBand(1.4, .recession, "deflation scare"), MacroBand(2, .early, "reflating from lows"), MacroBand(2.5, .neutral, "well-anchored"), MacroBand(3, .late, "expectations rising"), MacroBand(999999, .late, "de-anchoring")]),
        MacroIndicator("Avg hourly earnings YoY", .inflation, 3.15, .pct, importance: 2, oddsWeight: 0, timing: .lagging, source: "CES0500000003",
            descriptor: "Average hourly earnings growth year-over-year; wage pressure from labor-market tightness — firm wages above the ~3.3% pace consistent with 2% inflation are a classic late-cycle feature, soft wages signal slack.",
            bands: [MacroBand(2.5, .early, "labor slack"), MacroBand(3.5, .neutral, "normalizing"), MacroBand(4.5, .late, "firm/sticky"), MacroBand(999999, .late, "wage-price pressure")]),
        MacroIndicator("WTI crude YoY", .inflation, 31.13, .pct, importance: 1, oddsWeight: 4, timing: .leading, source: "DCOILWTICO",
            descriptor: "WTI crude oil price versus a year ago; energy is a cyclical catalyst — sharp spikes precede nearly every US recession, while deep collapses flag demand destruction.",
            bands: [MacroBand(-35, .recession, "demand destruction"), MacroBand(-10, .early, "disinflationary relief"), MacroBand(15, .neutral, "range-bound"), MacroBand(40, .late, "energy firming"), MacroBand(999999, .late, "oil shock")]),
        // --- Rates & policy ---
        MacroIndicator("10y-3m curve", .rates, 0.82, .pct, importance: 3, oddsWeight: 20, timing: .leading, source: "T10Y3M",
            descriptor: "Spread of the 10-year over the 3-month Treasury yield; the single most reliable recession lead, with deep inversion preceding downturns by roughly a year. Now positively sloped after un-inverting, so no recession signal.",
            bands: [MacroBand(-0.5, .recession, "deeply inverted"), MacroBand(0, .late, "inverted"), MacroBand(0.5, .neutral, "flat"), MacroBand(1.5, .neutral, "positively sloped"), MacroBand(2.5, .early, "steep"), MacroBand(999999, .early, "very steep")]),
        MacroIndicator("10y-2y curve", .rates, 0.5, .pct, importance: 2, oddsWeight: 12, timing: .leading, source: "T10Y2Y",
            descriptor: "10-year minus 2-year Treasury spread; a classic gauge of growth and policy expectations that corroborates the 3m-10y. Positive and normalized, confirming the curve is no longer flashing recession.",
            bands: [MacroBand(-0.3, .recession, "deeply inverted"), MacroBand(0, .late, "inverted"), MacroBand(0.4, .neutral, "flat"), MacroBand(1.2, .neutral, "positively sloped"), MacroBand(2, .early, "steep"), MacroBand(999999, .early, "very steep")]),
        MacroIndicator("10y real rate", .rates, 2.35, .pct, importance: 2, oddsWeight: 3, timing: .leading, source: "DFII10",
            descriptor: "10-year TIPS yield — the real cost of long-term capital; readings near multi-year highs are the most restrictive in over a decade, pressuring equity valuations and rate-sensitive demand — a late-cycle lean.",
            bands: [MacroBand(0, .early, "negative/accommodative"), MacroBand(0.75, .early, "low/easy"), MacroBand(1.5, .neutral, "moderate"), MacroBand(2.25, .late, "restrictive"), MacroBand(3, .late, "very restrictive"), MacroBand(999999, .recession, "extremely restrictive")]),
        MacroIndicator("Curve 6-mo trend", .rates, 48, .bps, importance: 2, oddsWeight: 6, timing: .leading, source: "T10Y3M",
            descriptor: "Six-month change in the 10y-3m curve, capturing un-inversion momentum. Orderly re-steepening off a flat base reads as normalization, not the crash-driven bull-steepener that front-runs recessions.",
            bands: [MacroBand(-75, .late, "re-flattening"), MacroBand(-15, .neutral, "flattening"), MacroBand(40, .neutral, "stable"), MacroBand(100, .neutral, "normalizing"), MacroBand(175, .late, "rapid steepening"), MacroBand(999999, .recession, "bull-steepening off inversion")]),
        MacroIndicator("Fed funds vs r*", .rates, 0.6, .pct, importance: 2, oddsWeight: 5, timing: .leading, source: "estimate",
            descriptor: "Effective fed funds minus estimated nominal neutral (r* plus the 2% inflation target); a positive gap marks a restrictive policy stance (late-cycle), and ongoing cuts narrow it back toward neutral.",
            bands: [MacroBand(-1, .early, "very accommodative"), MacroBand(-0.25, .early, "easy"), MacroBand(0.25, .neutral, "near neutral"), MacroBand(1.25, .late, "modestly restrictive"), MacroBand(2.25, .late, "restrictive"), MacroBand(999999, .recession, "very restrictive")]),
        MacroIndicator("Real fed funds rate", .rates, 1, .pct, importance: 2, oddsWeight: 5, timing: .leading, source: "estimate",
            descriptor: "Effective fed funds less core PCE inflation; a real rate at the high end of neutral-rate estimates is a restrictive, late-cycle policy stance that weighs on credit-sensitive activity.",
            bands: [MacroBand(-1, .early, "deeply negative"), MacroBand(0, .early, "negative/accommodative"), MacroBand(0.75, .neutral, "near neutral"), MacroBand(1.75, .late, "restrictive"), MacroBand(2.75, .late, "very restrictive"), MacroBand(999999, .recession, "extremely restrictive")]),
        // --- Money & liquidity ---
        MacroIndicator("Real M2 growth", .money, 1.99, .pct, importance: 2, oddsWeight: 6, timing: .leading, source: "M2REAL",
            descriptor: "YoY growth of inflation-adjusted M2 — the broad-money fuel gauge. Deep real contractions have preceded modern recessions; a barely-positive reading signals a still-tight but thawing liquidity backdrop.",
            bands: [MacroBand(-2, .recession, "contracting"), MacroBand(0, .late, "draining"), MacroBand(2, .neutral, "sluggish"), MacroBand(5, .early, "expanding"), MacroBand(999999, .early, "surging")]),
        MacroIndicator("NFCI conditions", .money, -0.56, .zscore, importance: 3, oddsWeight: 12, timing: .leading, source: "NFCI",
            descriptor: "Chicago Fed National Financial Conditions Index (100+ money, credit & leverage series), standardized so negative = easier than average. Loose conditions grease expansion; a swing positive is a premier, LEI-grade stress signal.",
            bands: [MacroBand(-0.3, .early, "loose"), MacroBand(0.2, .neutral, "neutral"), MacroBand(0.65, .late, "tightening"), MacroBand(999999, .recession, "stressed")]),
        MacroIndicator("SLOOS C&I tightening", .money, 0, .pct, importance: 3, oddsWeight: 14, timing: .leading, source: "DRTSCILM",
            descriptor: "Net share of banks tightening C&I lending standards (Fed Senior Loan Officer survey). A top leading indicator — net tightening above ~20% has front-run recessions by three to four quarters.",
            bands: [MacroBand(-10, .early, "easing"), MacroBand(5, .neutral, "balanced"), MacroBand(20, .late, "tightening"), MacroBand(999999, .recession, "credit crunch")]),
        MacroIndicator("C&I loan growth", .money, 8.39, .pct, importance: 2, oddsWeight: 5, timing: .lagging, source: "BUSLOANS",
            descriptor: "YoY growth in commercial & industrial bank loans — the business credit cycle in real time. Outright contraction is a late/recession tell, though it lags the turn; moderate growth confirms a firm mid-cycle.",
            bands: [MacroBand(-3, .recession, "contracting"), MacroBand(1, .late, "stalling"), MacroBand(6, .neutral, "moderate"), MacroBand(12, .early, "expanding"), MacroBand(999999, .late, "overheating")]),
        MacroIndicator("Reserves / GDP", .money, 10.3, .pct, importance: 1, oddsWeight: 3, timing: .leading, source: "estimate",
            descriptor: "Bank reserves as a share of GDP with the ON RRP buffer now drained to near zero — the system-liquidity cushion. As reserves drift toward 'scarce,' funding-stress risk rises (cf. the Sept 2019 repo spike).",
            bands: [MacroBand(8, .recession, "scarce"), MacroBand(11, .late, "adequate"), MacroBand(14, .neutral, "ample"), MacroBand(999999, .early, "abundant")]),
        // --- Credit ---
        MacroIndicator("HY OAS", .credit, 273, .bps, importance: 3, oddsWeight: 16, timing: .leading, source: "BAMLH0A0HYM2",
            descriptor: "ICE BofA US high-yield option-adjusted spread; the premier market gauge of default risk and credit tightness — very tight spreads signal late-cycle complacency, blowouts above ~600bp precede recessions.",
            bands: [MacroBand(300, .late, "very tight"), MacroBand(450, .neutral, "normal"), MacroBand(600, .late, "widening"), MacroBand(800, .recession, "stressed"), MacroBand(999999, .recession, "crisis")]),
        MacroIndicator("IG OAS", .credit, 81, .bps, importance: 2, oddsWeight: 9, timing: .leading, source: "BAMLC0A0CM",
            descriptor: "Investment-grade corporate option-adjusted spread; broad credit-conditions barometer — historically tight now, confirming the loose financial conditions typical of late cycle.",
            bands: [MacroBand(100, .late, "very tight"), MacroBand(140, .neutral, "normal"), MacroBand(190, .late, "widening"), MacroBand(250, .recession, "stressed"), MacroBand(999999, .recession, "crisis")]),
        MacroIndicator("HY spread 6mo dir", .credit, -35, .bps, importance: 2, oddsWeight: 12, timing: .leading, source: "estimate",
            descriptor: "6-month change in high-yield OAS; credit momentum — narrowing reads risk-on/early, while a sustained widening turn is one of the earliest and most reliable recession tells.",
            bands: [MacroBand(-25, .early, "narrowing"), MacroBand(25, .neutral, "stable"), MacroBand(75, .late, "drifting wider"), MacroBand(150, .late, "widening"), MacroBand(999999, .recession, "surging")]),
        MacroIndicator("Excess bond premium", .credit, -20, .bps, importance: 3, oddsWeight: 16, timing: .leading, source: "estimate",
            descriptor: "Gilchrist-Zakrajsek excess bond premium — the slice of credit spreads unexplained by fundamentals, a pure read on investor risk appetite and a top-tier recession predictor when it spikes; currently negative (loose/complacent).",
            bands: [MacroBand(-5, .late, "loose"), MacroBand(20, .neutral, "neutral"), MacroBand(55, .late, "tightening"), MacroBand(100, .recession, "stressed"), MacroBand(999999, .recession, "spiking")]),
        MacroIndicator("EM sovereign spread", .credit, 335, .bps, importance: 1, oddsWeight: 5, timing: .leading, source: "estimate",
            descriptor: "Emerging-market USD sovereign spread (EMBI Global / ICE BofA); global risk-appetite and dollar-funding-stress gauge — compressed spreads confirm calm, risk-on conditions, blowouts flag global contagion.",
            bands: [MacroBand(300, .early, "very tight"), MacroBand(400, .neutral, "calm"), MacroBand(500, .late, "elevated"), MacroBand(650, .late, "stressed"), MacroBand(999999, .recession, "crisis")]),
        MacroIndicator("HY default rate", .credit, 2.8, .pct, importance: 2, oddsWeight: 5, timing: .lagging, source: "estimate",
            descriptor: "US high-yield trailing-12-month default rate; the realized-loss confirmation of the credit cycle — lagging but definitive, and its rising trend marks late-cycle deterioration; currently low, below the ~3.5-4% long-run average.",
            bands: [MacroBand(2.5, .early, "very low"), MacroBand(4, .neutral, "benign"), MacroBand(6, .late, "rising"), MacroBand(8, .recession, "elevated"), MacroBand(999999, .recession, "spiking")]),
        // --- Equity & market ---
        MacroIndicator("Shiller CAPE", .market, 41.8, .ratio, importance: 2, oddsWeight: 0, timing: .leading, source: "multpl",
            descriptor: "Cyclically-adjusted P/E; extreme readings mark late-cycle valuation risk and cap forward returns, though it is a poor short-term timing tool.",
            bands: [MacroBand(16, .early, "cheap"), MacroBand(24, .neutral, "fair"), MacroBand(32, .late, "elevated"), MacroBand(999999, .late, "extreme")]),
        MacroIndicator("Fwd EPS revision breadth", .market, 11, .pct, importance: 2, oddsWeight: 4, timing: .leading, source: "estimate",
            descriptor: "Net share of firms seeing upward forward-EPS revisions; positive breadth confirms expansion, a roll to net downgrades leads earnings recessions.",
            bands: [MacroBand(-20, .recession, "collapsing"), MacroBand(-5, .late, "net downgrades"), MacroBand(5, .neutral, "mixed"), MacroBand(999999, .early, "net upgrades")]),
        MacroIndicator("S&P 500 vs 200-day", .market, 7.5, .pct, importance: 2, oddsWeight: 4, timing: .leading, source: "estimate",
            descriptor: "Distance of the S&P 500 from its 200-day average; price above a rising 200-day is a durable expansion signal, a sustained break warns of contraction.",
            bands: [MacroBand(-8, .recession, "breakdown"), MacroBand(0, .late, "below trend"), MacroBand(4, .neutral, "at trend"), MacroBand(999999, .early, "uptrend")]),
        MacroIndicator("Breadth (% above 200d)", .market, 62, .pct, importance: 1, oddsWeight: 3, timing: .leading, source: "estimate",
            descriptor: "Share of S&P constituents above their 200-day average; broad participation is healthy, narrowing to a thin mega-cap tape is a late-cycle tell.",
            bands: [MacroBand(25, .recession, "washed out"), MacroBand(45, .late, "narrowing"), MacroBand(65, .neutral, "healthy"), MacroBand(999999, .early, "broad")]),
        MacroIndicator("Cyclicals vs defensives", .market, 0.7, .zscore, importance: 2, oddsWeight: 0, timing: .leading, source: "estimate",
            descriptor: "Relative strength of cyclical vs defensive sectors; cyclical leadership signals risk-on expansion, defensive leadership flags slowdown.",
            bands: [MacroBand(-1.5, .recession, "defensives dominate"), MacroBand(-0.3, .late, "defensive tilt"), MacroBand(0.5, .neutral, "balanced"), MacroBand(999999, .early, "cyclicals lead")]),
        MacroIndicator("Copper/gold ratio", .market, -0.3, .zscore, importance: 1, oddsWeight: 0, timing: .leading, source: "estimate",
            descriptor: "Copper priced against gold, a growth/reflation gauge; copper strength signals expansion, gold leadership signals hedging and late-cycle caution.",
            bands: [MacroBand(-1.5, .recession, "deep risk-off"), MacroBand(-0.4, .late, "gold leadership"), MacroBand(0.5, .neutral, "range-bound"), MacroBand(999999, .early, "reflationary")]),
        MacroIndicator("VIX", .market, 14.89, .index, importance: 2, oddsWeight: 5, timing: .leading, source: "VIXCLS",
            descriptor: "Implied S&P volatility; ultra-low readings mark complacency, spikes into the 30s-40s coincide with stress and recessions.",
            bands: [MacroBand(15, .late, "complacent"), MacroBand(20, .neutral, "calm"), MacroBand(28, .late, "stressed"), MacroBand(40, .recession, "fear"), MacroBand(999999, .recession, "panic")]),
        MacroIndicator("Put/call ratio", .market, 0.85, .ratio, importance: 1, oddsWeight: 0, timing: .leading, source: "estimate",
            descriptor: "CBOE total put/call ratio, a contrarian sentiment gauge; very low readings show complacency/greed, spikes show fear and hedging.",
            bands: [MacroBand(0.9, .late, "complacent"), MacroBand(1.1, .neutral, "balanced"), MacroBand(999999, .recession, "fear")]),
        MacroIndicator("Small vs large caps", .market, -0.6, .zscore, importance: 1, oddsWeight: 0, timing: .leading, source: "estimate",
            descriptor: "Russell 2000 vs S&P 500 relative trend; small-cap leadership broadens the cycle, small-cap lag signals narrow, late-cycle leadership.",
            bands: [MacroBand(-1.5, .recession, "small caps crushed"), MacroBand(-0.3, .late, "large-cap narrow"), MacroBand(0.5, .neutral, "balanced"), MacroBand(999999, .early, "small caps lead")]),
        MacroIndicator("Trade-weighted USD (6mo)", .market, 0.99, .pct, importance: 1, oddsWeight: 3, timing: .leading, source: "DTWEXBGS",
            descriptor: "Six-month trend in the broad trade-weighted dollar; a rising dollar tightens global financial conditions, a surge signals stress.",
            bands: [MacroBand(-4, .early, "easing"), MacroBand(-1, .neutral, "soft"), MacroBand(3, .neutral, "stable"), MacroBand(7, .late, "firming"), MacroBand(999999, .recession, "surging")]),
    ]
}
